2025-03-12 17:15:38,864 - MultasGO - DEBUG - [logger.py:47] - Logger configurado com nível: DEBUG
2025-03-12 17:15:38,907 - MultasGO - INFO - [database.py:65] - Conexão com o banco de dados estabelecida com sucesso
2025-03-12 17:15:39,863 - MultasGO - INFO - [main.py:86] - Iniciando a aplicação MultasGO...
2025-03-12 17:15:42,273 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - select pg_catalog.version()
2025-03-12 17:15:42,274 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - [raw sql] {}
2025-03-12 17:15:42,698 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - select current_schema()
2025-03-12 17:15:42,700 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - [raw sql] {}
2025-03-12 17:15:43,134 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - show standard_conforming_strings
2025-03-12 17:15:43,134 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - [raw sql] {}
2025-03-12 17:15:43,689 - sqlalchemy.engine.Engine - INFO - [base.py:2699] - BEGIN (implicit)
2025-03-12 17:15:43,690 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - SELECT 1
2025-03-12 17:15:43,691 - sqlalchemy.engine.Engine - INFO - [base.py:1843] - [generated in 0.00061s] {}
2025-03-12 17:15:44,198 - MultasGO - INFO - [main.py:94] - Conexão com o banco de dados verificada com sucesso.
